apiVersion: v1
kind: Secret
metadata:
  name: catalogue-db-secret
  namespace: planification
  labels:
    app: catalogue-db
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: catalogue_db
  MYSQL_USER: catalogue_user
  MYSQL_PASSWORD: catalogue_pass
