apiVersion: v1
kind: Secret
metadata:
  name: emploi-db-secret
  namespace: planification
  labels:
    app: emploi-db
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: emploi_db
  MYSQL_USER: emploi_user
  MYSQL_PASSWORD: emploi_pass
