apiVersion: v1
kind: Secret
metadata:
  name: locaux-db-secret
  namespace: planification
  labels:
    app: locaux-db
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: locaux_db
  MYSQL_USER: locaux_user
  MYSQL_PASSWORD: locaux_pass
